#71 Potential fix for TypeError
TypeError: class or module required
C:/opscode/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.17.44-universal-mingw32/lib/chef/mixin/params_validate.rb:187:in `kind_of?'
...
C:/chef/local-mode-cache/cache/cookbooks/arcgis-enterprise/recipes/portal.rb:126:in `block in from_file'